// "export":"next build && next export"
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>
        {
          `.mySpan{
            color:red;
          }`
        }
      </style> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='/sc.js'></script> */}
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload' > */}

      {/* </Script> */}
      <main className={styles.main}>
        <div className={styles.imageWrap}>
          {/* <Image src='/homeimg.jpg' width={251} height={174} className={styles.myImg}></Image> */}
          <img src='/homeimg.jpg' alt="huntng coder img" width={174} height={174} className={styles.myImg} />
        </div>
        <h1 className={styles.title}>
          {/* <span className="mySpan dummy">Hunting Coder</span> */}
          <span className="mySpan">&lt;Hunting Coder/&gt;</span>
          {/* <a href="https://nextjs.org">Next.js!</a> */}
        </h1>
        <div className={styles.h2}>
          <h2>Latest Blogs</h2>
          <div >
            <h3 className={styles.h3}>how to learn next</h3>
            <p className={styles.p}>javascript is the language used to design logic for the web Lorem ipsum dolor sit amet.</p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div >
            <h3 className={styles.h3}>how to learn next</h3>
            <p className={styles.p}>javascript is the language used to design logic for the web Lorem ipsum dolor sit amet.</p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div >
            <h3 className={styles.h3}>how to learn next</h3>
            <p className={styles.p}>javascript is the language used to design logic for the web Lorem ipsum dolor sit amet.</p>
            <button className={styles.btn}>Read more</button>
          </div>
        </div>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>*/}
    </div>
  )
}
